version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "reqwest"
        versions: [">= 0.13.0"]
